#!/usr/bin/env sh

export COMPOSE_PROJECT_NAME="$(basename $(dirname $(dirname $(realpath $0))))"
export COMPOSE_FILE="$(dirname $0)/docker-compose.yml"

docker-compose run -u "$(id -u):$(id -g)" --rm npm /usr/local/bin/yarn "$@"
exit $?
